[package]
name = "beacn-mic-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
strum = { version = "0.27.1", features = ["strum_macros", "derive"] }
byteorder = "1.5.0"

# Used for Bass Enhancement Presets
once_cell = "1.20.3"
simplelog = "0.12.2"
log = "0.4.26"
anyhow = "1.0.96"

rusb = "0.9.4"