[package]
name = "beacn-mic-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
strum = { version = "0.27.1", features = ["strum_macros", "derive"] }
enum-map = "2.7.3"

byteorder = "1.5.0"

log = "0.4.26"
anyhow = "1.0.96"

rusb = "0.9.4"