[package]
name = "beacn-lib"
version = "0.2.2"
edition = "2024"

[features]
default = []

# These two get passed forward to nusb for use in async environments
async = []
tokio = ["dep:tokio", "tokio/time", "nusb/tokio", "async"]
async-rt = ["nusb/smol", "async"]

[dependencies]
strum = { version = "0.28", features = ["strum_macros", "derive"] }
enum-map = "2.7"

byteorder = "1.5.0"

log = "0.4.33"
anyhow = "1"

nusb = "0.2"

async-trait = "0.1"
async-lock = "3.4"

oneshot = { version = "0.2", features = ["std", "async"] }

futures-lite = "2.6"

# Used for Managing Interaction threads
flume = "0.12"

# Used to verify Mix / Mix Create image data
jpeg-decoder = "0.3"

# Easier Error Handling
thiserror = "2.0"

# Tokio Spawner
tokio = { version = "1", optional = true, default-features = false, features = ["rt"] }

# This replaces std::time in all environments
web-time = "1.1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# async-io include errno and polling, neither of which are wasm compatible, so we
# exclude it on wasm, and reimplement it with more appropriate crates
async-io = "2.6"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "=0.2.126"
wasm-bindgen-futures = "0.4"
gloo-timers = { version = "0.4", features = ["futures"] }


[dev-dependencies]
env_logger = "0.11.11"

# We don't use rt-multi-thread in the examples, but we do have a runtime wrapper that needs
tokio = { version = "1", default-features = false, features = ["rt", "sync", "macros"] }
image = { version = "0.25", features = ["jpeg"] }

# Used for general timers
futures-timer = { version = "3.0.4", features = ["wasm-bindgen"] }

# Used in the wasm_example to compile wasm
wasm-bindgen-cli-support = "=0.2.126"

# Used in the wasm_example to serve files
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tiny_http = "0.12"

# WASM Features
[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
web-sys = { version = "0.3.103", features = ["console", "Window", "CustomEvent", "CustomEventInit"] }


[[example]]
name = "enumerate"

[[example]]
name = "enumerate_async"
required-features = ["async"]

[[example]]
name = "hotplug"

[[example]]
name = "hotplug_async"
required-features = ["async"]

[[example]]
name = "audio"

[[example]]
name = "audio_async"
required-features = ["async"]

[[example]]
name = "controller"

[[example]]
name = "controller_async"
required-features = ["async"]